version: "2"

run:
  timeout: 5m
  relative-path-mode: gitroot

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - goconst
    - misspell
    - unconvert
    - unused
  exclusions:
    warn-unused: true
    paths:
      - web
      - .github
  settings:
    misspell:
      locale: US
